### ISSUE TITLE
path disk device shows undefined pool in gui

### ISSUE THREAD

**Issue by vosdev** [canonical/lxd-ui#1018]
![image](https://github.com/user-attachments/assets/247874be-132b-47c7-8036-866dcd5a4811)

links to `/ui/project/default/storage/pool/undefined`

Path passthrough storage is not part of a pool and should not show `on pool <pool>`. Maybe it would be better to show `Host path /data/media/` instead of `Volume /data/media` when it is a path mount
![image](https://github.com/user-attachments/assets/9dff03d0-81cb-48a7-bd2c-e0c50ec35650)

yaml config for clarity:
```
devices:
  nfs-media:
    path: /data/media
    source: /data/media
    type: disk
```
