### ISSUE TITLE
Feature Request: Support for unmanaged bridges

### ISSUE THREAD

**Issue by vosdev** [canonical/lxd-ui#1232]
I need my instances on my host network. Currently this is not supported via the UI.

My network yaml:
```
name: ovs0
description: ''
type: bridge
config: {}
```

Adding networks to instances/profiles must be done via yaml:

![Image](https://github.com/user-attachments/assets/89782b71-c178-4a54-b855-cc53e08231c3)

This is my profile config:
```yaml
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: ovs0
    type: nic
```

And the instance overview is empty

![Image](https://github.com/user-attachments/assets/a7660a8a-4f35-4880-9044-de485b638969)
