### ISSUE TITLE
security.acls: '' added to physical networks causing destructive issues

### ISSUE THREAD

**Issue by vosdev** [canonical/lxd-ui#1256]
Hey it's me again,

So I have this physical network:
```
project: default
name: guests
description: ''
type: physical
config:
  volatile.last_state.created: 'false'
  ipv4.ovn.ranges: 172.25.0.0-172.25.255.255
  ipv4.gateway: 192.168.3.1/24
  ipv4.routes: 172.25.0.0/16
  ipv4.routes.anycast: 'true'
  security.acls: ''
```

that last line keeps getting added by, I think, the UI. **And it's causing destructive issues.** ⚡
 I cannot make any changes to the network unless I delete this line it in the yaml view.

for example when I try to remove the ipv4.routes.anycast option:

![Image](https://github.com/user-attachments/assets/56e0461b-3fd5-4600-88ca-e021d446ea65)

What's worse is that when I try to access  the network via the cli, **all network settings get deleted**.

![Image](https://github.com/user-attachments/assets/4d3396a3-c3d7-47f0-90e1-388094b0f7bb)

I can see the settings disappear in my browser tab the second I execute the show command.

![Image](https://github.com/user-attachments/assets/3cb84579-ebcc-458a-8766-ffde85a64e81)
