### ISSUE TITLE
Feature Request: Custom grafana metrics url

### ISSUE THREAD

**Issue by vosdev** [canonical/lxd-ui#1278]
The metrics link currently only works with the "official" LXD dashboard and your prometheus job **must be** named `lxd`

https://github.com/canonical/lxd-ui/blob/0b0460608420a1de07a3b4bfa2ab2eb3a53d4e6b/src/pages/instances/InstanceDetail.tsx#L60

This dashboard has very limited amount of metrics. You have to scroll down all the way and manually open a panel to be able to see the selected instance. Unfortunately grafana also does not offer a way  to automatically open the panel.

I would like to request the feature to be able to customize the url. Allow us to configure a grafana url of our choosing and give us the option to populate that url with variables for the project and instance name.

Unfortunately not familiar with typescript so I don't know what the variables would look like but what I'm referring to is to end up with something like:

```yaml
#current 
user.grafana_base_url: https://192.168.3.185:3000/d/bGY-LSB7k/lxd

#suggested 
user.grafana_url: https://192.168.3.185:3000/d/rYdddlPWk/node-exporter-full?orgId=1&var-nodename=${instance}&refresh=1m

# this will still support the 'official'  lxd dashboard like so:
user.grafana_url: https://192.168.3.185:3000/d/bGY-LSB7k/lxd?orgId=1&var-job=lxd&var-project=${project}&var-name=${instance}
```

Why? With this feature you can link your node exporter dashboards to your instances and get complete metrics for your instances. Or you can use your organization's preferred dashboards. Or you can use the official LXD dashboard! Whichever you prefer.

This feature will also allow for a metric button for your lxd hosts mentioned in https://github.com/canonical/lxd-ui/issues/1261#issuecomment-2918862927. Maybe through a separate config like `user.grafana_url_hosts` and `user.grafana_url_instances`?
