### ISSUE TITLE
Cluster restore failure doesn't show in ui

### ISSUE THREAD

**Issue by vosdev** [canonical/lxd-ui#1345]
I have a cluster node that refuses to restore

via cli:
```
root@node2:~# lxc cluster restore node2
Are you sure you want to restore cluster member "node2"? (yes/no) [default=no]: yes
Error: Failed to wait for migration to finish: Instance move to destination failed on source: Failed migration on source: Error from migration control target: Failed creating instance on target: Cannot create volume, already exists on migration target storage
```

debug logs:
```
location: node2
metadata:
  context:
    class: task
    description: Creating instance
    err: 'Error transferring instance data: Failed migration on target: Failed creating
      instance on target: Cannot create volume, already exists on migration target
      storage'
    operation: 904e7313-7a3f-4fb2-ab2b-965244bce62a
    project: default
  level: debug
  message: Failure for operation
timestamp: "2025-06-29T15:35:22.697451573+02:00"
type: logging


location: node2
metadata:
  class: task
  created_at: "2025-06-29T15:35:22.654471532+02:00"
  description: Creating instance
  err: 'Error transferring instance data: Failed migration on target: Failed creating
    instance on target: Cannot create volume, already exists on migration target storage'
  id: 904e7313-7a3f-4fb2-ab2b-965244bce62a
  location: node2
  may_cancel: false
  metadata: null
  resources:
    containers:
    - /1.0/instances/c5
    instances:
    - /1.0/instances/c5
  status: Failure
  status_code: 400
  updated_at: "2025-06-29T15:35:22.654471532+02:00"
project: default
timestamp: "2025-06-29T15:35:22.697574194+02:00"
type: operation
```

But this is not visible from the ui at all. 

The UI simply shows "Online, Fully operational" for a few seconds and then goes back to "Evacuated - Unavailable due to maintenance"

![Image](https://github.com/user-attachments/assets/11a45d35-9956-4c24-8993-7769c99040d9)

I had to resort to the cli to figure out what was wrong. The issue I'm facing is related to  https://github.com/canonical/lxd/issues/15877 but if a restore fails for any reason it should show the error in the UI :)
