### ISSUE TITLE
LXD UI with Traefik

### ISSUE THREAD

**Issue by jefferyb** [canonical/lxd-ui#523]
Hello,

I am hoping to get some guidance on using Traefik to proxy requests to the LXD UI. I have Traefik successfully configured for other applications, but I am encountering challenges when attempting to integrate it with LXD.

If anyone has a working example of Traefik routing to the LXD UI, lxd.example.com, and login with the cert, I would greatly appreciate it if you could share it.

I tried this, but not sure what I'm missing

```
http:
  routers:
    lxd-ui:
      rule: "Host(`lxd.example.com`)"
      entryPoints:
        - websecure
      tls:
        certResolver: leresolver
        options: lxd-ui@file
      service: lxd-ui
      middlewares:
        - lxd-ui-passtlsclientcert

  services:
    lxd-ui:
      loadBalancer:
        servers:
          - url: https://xxx.xxx.xxx.xxx:8443

  middlewares:
    lxd-ui-passtlsclientcert:
      passTLSClientCert:
        pem: true

tls:
  options:
    lxd-ui:
      clientAuth:
        clientAuthType: RequireAnyClientCert
```

Thank you for your time and assistance.
-Jeffery
